# Generated by Django 6.0 on 2025-12-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='remarks',
        ),
    ]
